### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dy**

### CODE REVIEW

**Comment by bennypowers** [comment]
Thanks!

I don't recommend using this though, since the proposal was dropped in favour of a new one called "DOM Parts"

if you're looking for something similar try https://github.com/justinfagnani/stampino/

**Comment by dy** [comment]
Oh, thanks for letting know!
I'll check out.
Also curious to compare [jexpr](https://github.com/justinfagnani/jexpr) agains [subscript](https://github.com/spectjs/subscript), that seems to serve same purpose, will give it a shot.

**Comment by dy** [comment]
Ok, just compared. Subscript seems to be somewhat more efficient in terms of perf/size/extensibility.

**Comment by dy** [comment]
Ok, subscript seems to be somewhat more efficient in terms of performance/size.
Also - good to know that DOM Parts doesn't necessarily supersedes Template Instantiation, but provides underlying mechanism.

**Pull request merged**
